version: '3.8'

services:
  backend:
    build:
      context: ./back
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./front
    container_name: nextjs-app
    ports:
      - "3000:3000"
    restart: unless-stopped
