version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vnd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./back
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./front
    container_name: nextjs-app
    ports:
      - "3001:3000"
    restart: unless-stopped
