name: CI/CD with Docker

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Сборка и деплой через Docker Compose
        run: |
          docker-compose down
          docker-compose build
          docker-compose up -d
